### PR TITLE
drop the need for OBJ_CAST() when logging netlink objects

### PR DESCRIPTION
**Pull request by KanjiMonster**
Provide appropriate ``operator<<``s for various `rtnl_*` structs instead of forcing callers to `OBJ_CAST()` them, and drop `OBJ_CAST()` from all users.

## Motivation and Context

For some netlink structs we have a `operator<<`, for others these must be cast to `nl_object *` via `OBJ_CAST()`. This makes this error prone, as one might forget to hast (which then causes just he object's address to be printed, or add a `OBJ_CAST()` when one isn't needed, which may even cause crashes if the cast object isn't a `nl_object` (e.g. `nl_addr`).

So handle this casting via appropriate `operator<<`s, and reduce the possibilities of errors.

## How Has This Been Tested?

Built and run tested with debugging enabled.

### CODE REVIEW

**Comment by KanjiMonster** [comment]
This issue already existed before, but was hidden due to the `OBJ_CAST()`.

**Comment by KanjiMonster** [comment]
Pushed fixes for the unearthed issues.

**Comment by rubensfig** [comment]
This MR will need to be rebased after #417, as it created a merge conflict locally for me.

**Comment by KanjiMonster** [comment]
Yepp, whichever you merge first the other one will need to be rebased.

**Comment by rubensfig** [comment]
Ready for rebase then

**Comment by KanjiMonster** [comment]
> Ready for rebase then

Too slow, already rebased. ;P

**Review by rubensfig — APPROVED** [review]

**Pull request merged**
